### ISSUE TITLE
filter startColorstr='$F8' 不能编译

### ISSUE THREAD

**Issue by pengfeiWang** [oklai/koala#130]
test.scss
color.scss

``` css
/* color.scss 文件内容 */
$F8:#f8f8f8;
```

``` css
/* test.css 文件内容 */
import 'color.scss'
.test{
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='$F8', endColorstr='$White',GradientType=1 );
 /* 没有编译这两个预先设置的变量 */
}
```

```

```
