### ISSUE TITLE
[Less] Unable to load import file properly with @import-once

### ISSUE THREAD

**Issue by hughgr** [oklai/koala#56]
a.less:

``` less
.setWidth (@w) {
    width: @w;
}
```

b.less

``` less
@import-once "a.less";
.test {
    .setWidth(5px);
}
```

Compile Error: `NameError: .setWidth is undefined`
